site_name: Documentation project

nav:
  - "Introducción":
      - Home: "index.md"
  - "Guía de usuarios":
      - Descripción: "descripcion.md"
      - Alcance: "alcance.md"
      - Objetivos: "objetivos.md"
  - About us: "about.md"

theme: readthedocs
